import usFlag from './assets/flags/us.svg'
import mxFlag from './assets/flags/mx.svg'
import hrFlag from './assets/flags/hr.svg'
import type { AppCopy, LanguageCode, LanguageOption } from './types'

export const APP_COPY: Record<LanguageCode, AppCopy> = {
  US: {
    brand: 'TSSRC — Trapezoidal Segmented Static Ring Core',
    nav: ['Inicio', 'Combinations', 'Tools'],
    newItem: 'New item',
    saveItem: 'Save item',
    calculate: 'Calculate',
    calculationTitle: 'Calculation',
    trapezoidTitle: 'Trapezoid',
    layersTitle: 'Layers',
    layersReadOnlyHint: 'Read-only mode. Unlock admin mode to edit combinations.',
    layersAdminHint: 'Admin mode enabled. You can add, edit and delete combinations.',
    layersUser: 'User',
    layersPin: 'PIN',
    layersUnlock: 'Unlock admin',
    layersLock: 'Lock admin',
    layersAdd: 'Add combination',
    layersSave: 'Save combination',
    layersCancel: 'Cancel edit',
    orderEditTitle: 'Editing item',
    orderEditHint: 'Confirm changes with the check button or cancel to discard edits.',
    layersEdit: 'Edit combination',
    layersThickness: 'Thickness target',
    layersCombination: 'Combination',
    layersLayerCount: 'Layers',
    layersFinalThickness: 'Final thickness',
    layerItemLabel: 'Layer',
    layerNoMatch: 'No layer combination found for the current THnom.',
    layersStatus: 'Status',
    layersUpdatedBy: 'Updated by',
    layersUpdatedAt: 'Updated at',
    layersNoData: 'No combinations loaded.',
    layersAdminInvalidPin: 'Invalid PIN. Try again.',
    layersActive: 'Active',
    layersInactive: 'Inactive',
    shrinkage: 'Shrinkage (%)',
    tolerance: 'Tolerance (%)',
    noItemsForCalculation: 'Add at least one item before calculating.',
    alertsConfirmTitle: 'Alerts detected. Continue anyway?',
    orderItemsTitle: 'Items in current sales order',
    emptyOrderItems: 'No items added yet.',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    labels: {
      ID: 'ID',
      OD: 'OD',
      TH: 'TH',
      quantity: 'Quantity',
      salesOrder: 'Sales Order',
      position: 'Pos.'
    },
    themeDark: 'Dark',
    themeLight: 'Light',
    selectorLabel: 'Language'
  },
  MX: {
    brand: 'TSSRC — Trapezoidal Segmented Static Ring Core',
    nav: ['Inicio', 'Combinaciones', 'Herramientas'],
    newItem: 'Nuevo item',
    saveItem: 'Guardar item',
    calculate: 'Calcular',
    calculationTitle: 'Calculo',
    trapezoidTitle: 'Trapecio',
    layersTitle: 'Capas',
    layersReadOnlyHint: 'Modo solo lectura. Desbloquea modo admin para editar combinaciones.',
    layersAdminHint: 'Modo admin activo. Puedes agregar, editar y eliminar combinaciones.',
    layersUser: 'Usuario',
    layersPin: 'PIN',
    layersUnlock: 'Desbloquear admin',
    layersLock: 'Bloquear admin',
    layersAdd: 'Agregar combinacion',
    layersSave: 'Guardar combinacion',
    layersCancel: 'Cancelar edicion',
    orderEditTitle: 'Editando item',
    orderEditHint: 'Confirma los cambios con el boton check o cancela para descartarlos.',
    layersEdit: 'Editar combinacion',
    layersThickness: 'Espesor objetivo',
    layersCombination: 'Combinacion',
    layersLayerCount: 'Capas',
    layersFinalThickness: 'Espesor final',
    layerItemLabel: 'Capa',
    layerNoMatch: 'No se encontro una combinacion de capas para el THnom actual.',
    layersStatus: 'Estado',
    layersUpdatedBy: 'Actualizado por',
    layersUpdatedAt: 'Actualizado el',
    layersNoData: 'No hay combinaciones cargadas.',
    layersAdminInvalidPin: 'PIN invalido. Intenta de nuevo.',
    layersActive: 'Activa',
    layersInactive: 'Inactiva',
    shrinkage: 'Encogimiento (%)',
    tolerance: 'Tolerancia (%)',
    noItemsForCalculation: 'Agrega al menos un item antes de calcular.',
    alertsConfirmTitle: 'Se detectaron alertas. Deseas continuar?',
    orderItemsTitle: 'Items de la orden de venta actual',
    emptyOrderItems: 'Aun no hay items cargados.',
    actions: 'Acciones',
    edit: 'Editar',
    delete: 'Eliminar',
    labels: {
      ID: 'ID',
      OD: 'OD',
      TH: 'TH',
      quantity: 'Cantidad',
      salesOrder: 'Orden de Venta',
      position: 'Pos.'
    },
    themeDark: 'Oscuro',
    themeLight: 'Claro',
    selectorLabel: 'Idioma'
  },
  HVR: {
    brand: 'TSSRC — Trapezoidal Segmented Static Ring Core',
    nav: ['Inicio', 'Kombinacije', 'Alati'],
    newItem: 'Novi item',
    saveItem: 'Spremi stavku',
    calculate: 'Izracunaj',
    calculationTitle: 'Izracun',
    trapezoidTitle: 'Trapez',
    layersTitle: 'Slojevi',
    layersReadOnlyHint: 'Nacin samo za citanje. Otkljucaj admin nacin za uredivanje kombinacija.',
    layersAdminHint: 'Admin nacin je aktivan. Mozes dodati, urediti i obrisati kombinacije.',
    layersUser: 'Korisnik',
    layersPin: 'PIN',
    layersUnlock: 'Otkljucaj admin',
    layersLock: 'Zakljucaj admin',
    layersAdd: 'Dodaj kombinaciju',
    layersSave: 'Spremi kombinaciju',
    layersCancel: 'Odustani od uredivanja',
    orderEditTitle: 'Uredujes stavku',
    orderEditHint: 'Potvrdi promjene gumbom s kvacicicom ili odustani za ponistenje.',
    layersEdit: 'Uredi kombinaciju',
    layersThickness: 'Ciljana debljina',
    layersCombination: 'Kombinacija',
    layersLayerCount: 'Slojevi',
    layersFinalThickness: 'Konacna debljina',
    layerItemLabel: 'Sloj',
    layerNoMatch: 'Nije pronadena kombinacija slojeva za trenutni THnom.',
    layersStatus: 'Status',
    layersUpdatedBy: 'Azurirao',
    layersUpdatedAt: 'Azurirano',
    layersNoData: 'Nema ucitanih kombinacija.',
    layersAdminInvalidPin: 'Neispravan PIN. Pokusaj ponovno.',
    layersActive: 'Aktivno',
    layersInactive: 'Neaktivno',
    shrinkage: 'Skupljanje (%)',
    tolerance: 'Tolerancija (%)',
    noItemsForCalculation: 'Dodaj barem jednu stavku prije izracuna.',
    alertsConfirmTitle: 'Otkrivene su upozorbe. Zelis li nastaviti?',
    orderItemsTitle: 'Stavke trenutnog prodajnog naloga',
    emptyOrderItems: 'Jos nema dodanih stavki.',
    actions: 'Radnje',
    edit: 'Uredi',
    delete: 'Obrisi',
    labels: {
      ID: 'ID',
      OD: 'OD',
      TH: 'TH',
      quantity: 'Kolicina',
      salesOrder: 'Prodajni nalog',
      position: 'Poz.',
    },
    themeDark: 'Tamno',
    themeLight: 'Svijetlo',
    selectorLabel: 'Jezik'
  }
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'US', label: 'United States', flagSrc: usFlag },
  { code: 'MX', label: 'Mexico', flagSrc: mxFlag },
  { code: 'HVR', label: 'Hrvatski', flagSrc: hrFlag }
]